# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/04 17:52:50 by dlesieur          #+#    #+#              #
#    Updated: 2025/07/04 17:52:57 by dlesieur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

## Please use configure script

all	: do_configure

do_configure	:
	./configure

clean	:
	./configure clean

re	: clean all
